config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    devise_for :users
    mount RailsAdmin::Engine => "/admin_manager", as: "rails_admin"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"

    resources :users, only: :show
    resources :currencies, only: %i(new create index)

    namespace :admin do
      post "/payment", to: "payments#create"
      post "/payment_all", to: "payments#create_all"
      resources :goal_results, only: %i(create new)
      resources :user_bets, only: :index
      resources :bets
      post "/update_bets", to: "bets#update_bets"
      resources :soccer_matches
      resources :statistics, only: :index
      root to: "soccer_matches#index"
    end

    resources :bets, only: :index do
      member do
        resources :user_bets, only: %i(new create)
      end
    end
    get "/user_bets", to: "user_bets#index"
  end
end

app/models/soccer_match.rb
class SoccerMatch < ApplicationRecord
  belongs_to :tournament
  belongs_to :home_team, class_name: Team.name, foreign_key: :home_id
  belongs_to :guest_team, class_name: Team.name, foreign_key: :guest_id

  has_many :bets, dependent: :destroy
  has_many :goal_results, dependent: :destroy
  has_many :user_bets, through: :bets

  delegate :name, to: :home_team, prefix: :home, allow_nil: true
  delegate :name, to: :guest_team, prefix: :guest, allow_nil: true
  delegate :name, to: :tournament, prefix: :tournament, allow_nil: true

  accepts_nested_attributes_for :goal_results, allow_destroy: true
  accepts_nested_attributes_for :bets, allow_destroy: true

  scope :newest, ->{order :time}

  validate :valid_match_time?

  private

  def valid_match_time?
    return if time >= Time.zone.today

    errors.add(:time, :invalid_match_time)
  end
end

app/controllers/admin/soccer_matches_controller.rb
class Admin::SoccerMatchesController < Admin::BaseController
  include EventsHelper
  authorize_resource

  before_action :load_soccer_match, only: %i(edit update show)
  before_action :load_teams_and_tournaments, only: %i(new edit)

  def index
    @pagy, @soccer_matches = pagy SoccerMatch.includes(:home_team, :guest_team)
                                             .newest
    @win = Currency.search_by_type(:win).sum(:amount)
    @lose = Currency.search_by_type(:lose).sum(:amount)
  end

  def create
    @soccer_match = SoccerMatch.new soccer_match_params
    if @soccer_match.save
      flash[:success] = t ".successful_create"
      redirect_to new_admin_soccer_match_path
    else
      flash.now[:danger] = t ".failure_create"
      render :new
    end
  end

  def new
    @soccer_match = SoccerMatch.new
  end

  def edit; end

  def update
    if @soccer_match.update soccer_match_params
      flash[:success] = t ".successful_update"
      redirect_to admin_root_path
    else
      flash.now[:danger] = t ".failure_update"
      load_teams_and_tournaments
      render :edit
    end
  end

  def show
    winners = @soccer_match.user_bets.load_result_bet true
    total_user_win = @soccer_match.user_bets.load_result_bet(true).sum(:amount)
    @total_win_amount = total_win_bet winners
    @total_amount = @soccer_match.user_bets.sum(:amount)
    @total_winner_has_rate = @total_win_amount - total_user_win
    @total_lose_amount = @soccer_match.user_bets.load_result_bet(false)
                                      .sum(:amount)
  end

  private

  def load_soccer_match
    @soccer_match = SoccerMatch.find_by(id: params[:id])
    return if @soccer_match

    flash[:danger] = t ".not_found_match"
    redirect_to admin_root_path
  end

  def soccer_match_params
    params.require(:soccer_match).permit(:home_id, :guest_id,
                                         :time, :tournament_id)
  end

  def load_teams_and_tournaments
    @teams = Team.all
    @tournaments = Tournament.all
  end
end

app/helpers/soccer_match_helper.rb
module SoccerMatchHelper
  def calculate_score team_id, soccer_match_id
    GoalResult.score(team_id, soccer_match_id).count
  end

  def time_handling match_time
    match_time.strftime(Settings.format_time)
  end

  def check_status_match status
    t "soccer_matches.#{status ? 'finished-status' : 'unfinished-status'}"
  end

  def load_result soccer_match
    result_home = calculate_score(soccer_match.home_team, soccer_match.id)
    result_guest = calculate_score(soccer_match.guest_id, soccer_match.id)
    return "win" if result_home > result_guest
    return "draw" if result_home == result_guest

    "lose"
  end

  def load_result_score soccer_match
    result_home = calculate_score(soccer_match.home_team, soccer_match.id)
    result_guest = calculate_score(soccer_match.guest_id, soccer_match.id)
    return "other" unless Bet.bet_types["h#{result_home}g#{result_guest}"]

    "h#{result_home}g#{result_guest}"
  end
end

app/views/admin/soccer_matches/_form.html.erb
<%= form_for(@soccer_match, url: yield(:url)) do |f| %>
  <%= f.label t(".tournaments"), class: "mt-3" %>
  <%= f.select :tournament_id, options_for_select(@tournaments.collect{ |t| [t.name, t.id] }), {}, class: "form-control" %>

  <%= f.label t(".home_team"), class: "mt-3" %>
  <%= f.select :home_id, options_for_select(@teams.collect{ |t| [t.name, t.id] }, @soccer_match.home_id), {}, class: "form-control" %>

  <%= f.label t(".guest_team"), class: "mt-3" %>
  <%= f.select :guest_id, options_for_select(@teams.collect{ |t| [t.name, t.id] }, @soccer_match.guest_id), {}, class: "form-control" %>

  <%= f.label t(".match_time"), class: "mt-3 row" %>
  <%= f.datetime_select :time %>

  <div class="mt-3 text-center">
    <%= f.submit yield(:btn_match), class: "btn btn-primary" %>
  </div>

<% end %>

app/views/admin/soccer_matches/_soccer_match.html.erb
<li class="list-unstyled mt-4 border">
  <div class="row mt-3 mb-3">
    <div class="col">
      <div class="soccer-match">
        <%= image_tag("/assets/football-logo/#{soccer_match.home_name}.png",size: "150x150") %>
      </div>
      <div class="row soccer-match">
        <%= soccer_match.home_name %>
      </div>
    </div>
    <div class="col">
      <div class="soccer-match">
        <span class="fw-bold"><%= t "soccer_matches.soccer_match.league", name: soccer_match.tournament_name %></span>
      </div>
      <div class="text-warning soccer-match">
          <%= check_status_match(soccer_match.status) %>
      </div>
      <div class="row h1 soccer-match">
        <%= calculate_score(soccer_match.home_team, soccer_match.id) %>
         -
        <%= calculate_score(soccer_match.guest_team, soccer_match.id) %>
      </div>
      <div class="soccer-match">
        <div class="dropdown">
          <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            <%= t ".action" %>
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            <% unless soccer_match.status %>
              <li><%= link_to t(".set_bet_btn"), admin_bets_path(match_id: soccer_match.id), method: :post, class: "dropdown-item" %></li>
              <li><%= link_to t(".edit_match_btn"), edit_admin_soccer_match_path(soccer_match.id), class: "dropdown-item" %></li>
              <li><%= link_to t(".update_core"), new_admin_goal_result_path(match_id: soccer_match.id), class: "dropdown-item" %></li>
            <% else %>
              <li><%= link_to t(".show_bet_win"), admin_user_bets_path(match_id: soccer_match.id), class: "dropdown-item" %></li>
              <li><%= link_to t(".show_bet_win_score"), admin_user_bets_path(match_id: soccer_match.id, score: true), class: "dropdown-item" %></li>
              <li>
              <%= link_to t(".show_match_btn"), admin_soccer_match_path(soccer_match.id), class: "dropdown-item" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>

      <div class="soccer-match">
        <%= time_handling(soccer_match.time) %>
      </div>
    </div>

    <div class="col">
      <div class="soccer-match">
        <%= image_tag("/assets/football-logo/#{soccer_match.guest_name}.png", size: "150x150") %>
        </div>
      <div class="row soccer-match">
        <%= soccer_match.guest_name %>
      </div>
    </div>
  </div>
</li>

app/views/admin/soccer_matches/edit.html.erb
<% provide(:title, t(".title")) %>
<% provide(:url, admin_soccer_match_path(params[:id])) %>
<% provide(:btn_match, t(".edit_btn")) %>
<h1 class="text-center"> <%= t".title" %> </h1>
<h5> <%= t".id", id: @soccer_match.id %></h5>

<div class="row mt-3 soccer-match">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/admin/soccer_matches/index.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
<div class="row">
  <canvas id="myChart" class="col" style="width:100%;max-width:600px"></canvas>
    <%= t(".total_income") + (@lose - @win).to_s %>
</div>

<ol><%= render @soccer_matches %></ol>
<%== pagy_nav(@pagy) %>

<%= content_tag :div, class: "chart", data: {win: @win, lose: @lose} do %>
<% end %>
<%= javascript_pack_tag "chart" %>

app/views/admin/soccer_matches/new.html.erb
<% provide(:title, t(".title")) %>
<% provide(:url, admin_soccer_matches_path) %>
<% provide(:btn_match, t(".new_btn")) %>
<h1 class="text-center"> <%= t".title" %> </h1>
<div class="row mt-3 soccer-match">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/admin/soccer_matches/show.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
<div class="mb-5 soccer-match h2">
  <%= t ".title_statistic" %>
</div>
<div class="row soccer-match ">
  <div class="col h3 row soccer-match">
    <div class="col">
      <%= image_tag("/assets/football-logo/#{@soccer_match.home_name}.png",size: "150x150") %>
    </div>
    <div class="col">
      <%= @soccer_match.home_name %>
    </div>
  </div>
  <div class="col row soccer-match">
    <div class="col h1 soccer-match">
      <%= calculate_score(@soccer_match.home_id, @soccer_match.id) %>
        -
      <%= calculate_score(@soccer_match.guest_id, @soccer_match.id) %>
    </div>
    <div class="row soccer-match text-center pt-1">
      <span class="text-danger"><%= t".finished" %></span>
    </div>
  </div>
  <div class="col h3 row soccer-match">
    <div class="col">
      <%= @soccer_match.guest_name %>
    </div>
    <div class="col">
      <%= image_tag("/assets/football-logo/#{@soccer_match.guest_name}.png",size: "150x150") %>
    </div>
  </div>
</div>

<div class="row soccer-match mt-5">
  <canvas id="myChart" class="col" style="width:100%;max-width:600px"></canvas>
  <div class="col h2">
    <%= t(".total_income") + (@total_amount - @total_win_amount).to_s %>
  </div>
</div>
<%= content_tag :div, class: "chart", data: {win: @total_winner_has_rate, lose: @total_lose_amount} do %>
<% end %>
<%= javascript_pack_tag "chart" %>