config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    devise_for :users
    mount RailsAdmin::Engine => "/admin_manager", as: "rails_admin"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"

    resources :users, only: :show
    resources :currencies, only: %i(new create index)

    namespace :admin do
      post "/payment", to: "payments#create"
      post "/payment_all", to: "payments#create_all"
      resources :goal_results, only: %i(create new)
      resources :user_bets, only: :index
      resources :bets
      post "/update_bets", to: "bets#update_bets"
      resources :soccer_matches
      resources :statistics, only: :index
      root to: "soccer_matches#index"
    end

    resources :bets, only: :index do
      member do
        resources :user_bets, only: %i(new create)
      end
    end
    get "/user_bets", to: "user_bets#index"
  end
end

app/models/user_bet.rb
class UserBet < ApplicationRecord
  belongs_to :user
  belongs_to :bet

  scope :newest, ->{order created_at: :desc}
  scope :load_result_bet, ->(result){where result_bet: result}

  scope :load_by_date, (lambda do |start_month, end_month|
    where(Settings.sql.sql_find_period,
          start_month, end_month)
  end)

  delegate :content, to: :bet, prefix: :bet, allow_nil: true
  delegate :rate, to: :bet, prefix: :bet, allow_nil: true

  validates :amount, presence: true,
          numericality: {greater_than_or_equal_to: 0}

  def self.search start_month, end_month
    return unless start_month && end_month

    UserBet.load_by_date start_month, end_month
  end
end

app/controllers/admin/user_bets_controller.rb
class Admin::UserBetsController < Admin::BaseController
  include SoccerMatchHelper
  authorize_resource

  before_action :load_match, :load_bet, :check_status_match, only: :index

  def index
    @q = UserBet.ransack amount_gteq: params.dig(:q, :amount_gteq)
    user_bets = @q.result.accessible_by(current_ability)
    @pagy, @user_bets = pagy user_bets, items: Settings.digits.digit_6
  end

  private

  def load_match
    param = params[:match_id] || params.dig(:q, :match_id)
    @match = SoccerMatch.find_by id: param
    return if @match

    flash[:warning] = t ".not_found_match"
    redirect_to admin_root_path
  end

  def load_bet
    @bet = if params[:score]
             @match.bets.find_by bet_type: load_result_score(@match)
           else
             @match.bets.find_by bet_type: load_result(@match)
           end
    return if @bet

    flash[:warning] = t ".not_found_bet"
    redirect_to admin_root_path
  end

  def check_status_match
    return if @match.status

    flash[:warning] = t ".match_not_begin"
    redirect_to admin_root_path
  end
end

app/controllers/user_bets_controller.rb
class UserBetsController < ApplicationController
  include UserBetsHelper
  authorize_resource
  before_action :logged_in_user, only: %i(new create index)
  before_action :load_bet, only: %i(new create)
  before_action :check_amount_bet, only: :create

  def new
    @user_bet = current_user.user_bets.new
  end

  def create
    money = params[:user_bet][:amount]
    current_user.currencies.new amount: money,
                                    currency_type_id: :lose
    current_user.user_bets.new user_bet_params
    begin
      User.transaction do
        current_user.save!
      end
    rescue StandardError
      flash[:warning] = t ".fails"
    else
      flash[:success] = t ".success"
    end
    redirect_to root_path
  end

  def index
    @q = UserBet.ransack amount_gteq: params.dig(:q, :amount_gteq)
    bets = @q.result.accessible_by(current_ability)
    @pagy, @user_bets = pagy bets.newest, items: Settings.digits.digit_6
  end

  private

  def user_bet_params
    params.require(:user_bet).permit(:amount, :bet_id)
  end

  def load_bet
    @bet = Bet.find_by(id: params[:id])
    return if @bet

    flash[:warning] = t ".not_found_bet"
    redirect_to root_path
  end

  def check_amount_bet
    flag = money_bet_valid? current_user, params[:user_bet][:amount]
    return if flag

    flash[:warning] = t ".amount_invalid"
    redirect_to new_user_bet_path
  end
end

app/helpers/user_bets_helper.rb
module UserBetsHelper
  include UsersHelper
  def money_bet_valid? user, money_bet
    sum_amount(user) > money_bet.to_i
  end

  def check_all_result_bet bet
    bet.user_bets.each do |user_bet|
      return false unless user_bet.result_bet
    end
    true
  end
end

app/views/admin/user_bets/_user_bet.html.erb
<li id="user_bet-<%= user_bet.id %>">
  <div class="row mt-3">
    <div class="col-md-4 text-center">
      <%= user_bet.bet_content %>:
      <%= user_bet.bet.soccer_match.home_name %>-
      <%= user_bet.bet.soccer_match.guest_name %>
    </div>
    <div class="col-md-2 text-center">
      <%= user_bet.amount %>
    </div>
    <div class="col-md-2 text-center">
      <%= user_bet.user.name %>
    </div>
    <div class="col-md-2 text-center">
      <%= time_ago_in_words(user_bet.created_at) %> <%= t ".intro" %>
    </div>
    <div class="col-md-2">
      <%= user_bet.result_bet ? t(".paymented") : (button_to t(".result_money"), admin_payment_path(user_bet_id: user_bet)) %>
    </div>
  </div>
</li>

app/views/admin/user_bets/index.html.erb
<% provide :title, t(".title") %>
<div class="row">
  <div class="col mt-3">
    <h3 class="text-danger text-primary">
      <%= t ".title" %>
    </h3>
    <%= search_form_for @q, url: admin_user_bets_path,
                        html: { method: :get } do |f| %>
        <%= f.hidden_field :match_id, value: @match.id %>
        <%= f.label :amount_gteq %>
        <%= f.search_field :amount_gteq %>

        <%= f.submit %>
    <% end %>
    <div class="row mt-3">
      <div class="col-md-1 text-primary">
        <%= t ".title_#" %>
      </div>
      <div class="col-md-3 text-primary">
        <%= t ".title_id" %>
      </div>
      <div class="col-md-2 text-center text-primary">
        <%= t ".title_amount" %>
      </div>
      <div class="col-md-2 text-center text-primary">
        <%= t ".title_user" %>
      </div>
      <div class="col-md-2 text-center text-primary">
        <%= t ".at" %>
      </div>
      <div class="col-md-2 text-primary">
        <%= t ".title_action" %>
      </div>
    </div>
    <ol class="user_bets">
      <%= render(@user_bets) || t(".empty") %>
    </ol>
    <%== pagy_nav @pagy %>
  </div>
  <div class="row offset-10">
    <%= button_to t(".payment_all"), admin_payment_all_path(bet_id: @bet.id) unless check_all_result_bet @bet%>
  </div>
</div>