config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    devise_for :users
    mount RailsAdmin::Engine => "/admin_manager", as: "rails_admin"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"

    resources :users, only: :show
    resources :currencies, only: %i(new create index)

    namespace :admin do
      post "/payment", to: "payments#create"
      post "/payment_all", to: "payments#create_all"
      resources :goal_results, only: %i(create new)
      resources :user_bets, only: :index
      resources :bets
      post "/update_bets", to: "bets#update_bets"
      resources :soccer_matches
      resources :statistics, only: :index
      root to: "soccer_matches#index"
    end

    resources :bets, only: :index do
      member do
        resources :user_bets, only: %i(new create)
      end
    end
    get "/user_bets", to: "user_bets#index"
  end
end

app/models/bet.rb
class Bet < ApplicationRecord
  belongs_to :soccer_match, foreign_key: :soccer_match_id

  has_many :user_bets, dependent: :destroy
  has_many :users, through: :user_bets

  scope :newest, ->{order created_at: :desc}

  enum bet_type: {win: 1, draw: 2, lose: 3, h0g0: 4, h0g1: 5, h1g0: 6, h1g1: 7,
                  other: 8}
end

app/controllers/admin/bets_controller.rb
class Admin::BetsController < Admin::BaseController
  include EventsHelper
  authorize_resource

  before_action :load_match, only: %i(create update_bets)
  before_action :check_status_match, only: :update_bets

  def create
    return unless check_bet_empty? @soccer_match

    begin
      CreateBetsJob.perform_in(1.second, @soccer_match.id)
      flash[:success] = t ".bets_default"
    rescue StandardError
      action_if_create_false
    end
  end

  def update_bets
    if @soccer_match.update bets_params
      flash[:success] = t ".success"
    else
      flash[:warning] = t ".fails"
    end
    redirect_to admin_root_path
  end

  private

  def bets_params
    params.require(:soccer_match)
          .permit(bets_attributes: [:id, :rate, :bet_type, :content])
  end

  def load_match
    @soccer_match = SoccerMatch.find_by id: params[:match_id]
    return if @soccer_match

    flash[:warning] = t ".match_not_found"
    redirect_to admin_root_path
  end

  def check_status_match
    return unless @soccer_match.status

    flash[:warning] = t ".match_finished"
    redirect_to admin_root_path
  end

  def action_if_create_false
    flash[:warning] = t ".fails"
    redirect_to admin_root_path
  end
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  authorize_resource
  before_action :logged_in_user, :load_match, only: :index

  def index
    @q = Bet.ransack content_cont: params.dig(:q, :content_cont)
    match_bets = @q.result
    @pagy, @bets = pagy match_bets.newest, items: Settings.digits.digit_6
  end

  private

  def load_match
    param = params[:match_id] || params.dig(:q, :match_id)
    @match = SoccerMatch.find_by id: param
    return if @match

    flash[:warning] = t ".not_found_match"
    redirect_to root_path
  end
end

app/views/bets/_bet.html.erb
<li id="bet-<%= bet.id %>">
  <div class="row mt-3">
    <div class="col-md-6 text-center">
      <%= bet.content %>
    </div>
    <div class="col-md-2">
      <%= bet.rate %>
    </div>
    <div class="col-md-4">
      <%= link_to t(".bet"), new_user_bet_path(id: bet.id) %>
    </div>
  </div>
</li>

app/views/bets/_bet_infor.html.erb
<div class="mt-3">
  <h3 class="text-center text-warning"><%= t ".info" %></h3>
  <div class="row fs-4">
    <div class="col-md-4 text-danger"><%=  t ".content" %></div>
    <div class="col-md-8"><%= bet.content %></div>
  </div>
  <div class="row fs-4">
    <div class="col-md-4 text-danger"><%= t ".rate" %></div>
    <div class="col-md-8"><%= bet.rate %></div>
  </div>
  <div class="row fs-4">
    <div class="col-md-4 text-danger"><%= t ".match" %></div>
    <div class="col-md-8">
      <%= bet.soccer_match.home_name %>-
      <%= bet.soccer_match.guest_name %>
    </div>
  </div>
</div>

app/views/bets/index.html.erb
<% provide :title, t(".list_bet") %>
<div class="row">
  <aside class="col-md-6">
    <div class="mt-3">
      <h3 class="text-center text-warning"><%= t ".infor_match" %></h3>
      <div class="row fs-4">
        <div class="col-md-4 text-danger"><%= t ".home" %></div>
        <div class="col-md-8"><%= @match.home_name %></div>
      </div>
      <div class="row fs-4">
        <div class="col-md-4 text-danger"><%= t ".guest" %></div>
        <div class="col-md-8"><%= @match.guest_name %></div>
      </div>
      <div class="row fs-4">
        <div class="col-md-4 text-danger"><%= t ".day" %></div>
        <div class="col-md-8"><%= I18n.l @match.time %></div>
      </div>
    </div>
  </aside>

  <div class="col-md-6 mt-3">
    <% if @bets.any? %>
      <h3 class="text-danger">
        <%= t ".list_bet" %>
      </h3>
      <%= search_form_for @q, url: bets_path,
                        html: { method: :get } do |f| %>
        <%= f.hidden_field :match_id, value: @match.id %>
        <%= f.label :content_cont %>
        <%= f.search_field :content_cont %>

        <%= f.submit %>
      <% end %>
      <div class="row border-bottom">
        <div class="col-md-1 fs-5 text-primary">
          <%= t ".title_#" %>
        </div>
        <div class="col-md-5 fs-5 text-center text-primary">
          <%= t ".title_content" %>
        </div>
        <div class="col-md-2 fs-5 text-primary">
          <%= t ".title_rate" %>
        </div>
        <div class="col-md-4 fs-5 text-primary">
          <%= t ".title_action" %>
        </div>
      </div>
      <ol class="bets">
        <%= render @bets %>
      </ol>
      <%== pagy_nav @pagy %>
    <% else %>
      <%= t ".empty" %>
    <% end %>
  </div>
</div>