config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    devise_for :users
    mount RailsAdmin::Engine => "/admin_manager", as: "rails_admin"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"

    resources :users, only: :show
    resources :currencies, only: %i(new create index)

    namespace :admin do
      post "/payment", to: "payments#create"
      post "/payment_all", to: "payments#create_all"
      resources :goal_results, only: %i(create new)
      resources :user_bets, only: :index
      resources :bets
      post "/update_bets", to: "bets#update_bets"
      resources :soccer_matches
      resources :statistics, only: :index
      root to: "soccer_matches#index"
    end

    resources :bets, only: :index do
      member do
        resources :user_bets, only: %i(new create)
      end
    end
    get "/user_bets", to: "user_bets#index"
  end
end

app/views/shared/_asider_admin.html.erb
<li>
  <i class="bi-person-circle fs-6">__<%= current_user.name %> </i>
</li>
<li class="nav-item">
  <%= link_to t("shared.asider_user.home"), admin_root_path, class: "nav-link py-3 px-2 bi-house fs-6" %>
</li>
<li class="nav-item">
  <%= link_to t("actions.Dashboard.menu"), Settings.dashboard_path, class: "nav-link py-3 px-2 bi-house fs-6" %>
</li>
<li class="nav-item">
  <%= link_to t(".create_soccer_match"), new_admin_soccer_match_path, class: "nav-link py-3 px-2 bi bi-chevron-double-right fs-6" %>
</li>
<li class="nav-item">
  <%= link_to t(".income_statistics"), admin_statistics_path, class: "nav-link py-3 px-2 bi bi-chevron-double-right fs-6" %>
</li>
<li class="nav-item">
  <%= link_to t(".setting"), edit_user_registration_path, class: "nav-link py-3 px-2 bi-wrench fs-6" %>
</li>
<li class="nav-item">
  <%= link_to t("shared.asider_user.log_out"), destroy_user_session_path, method: "delete", class: "nav-link py-3 px-2 bi-stop-circle-fill fs-6" %>
</li>

app/views/shared/_asider_user.html.erb
<li>
  <i class="bi-person-circle fs-6">__<%= current_user.name %></i>
</li>
<li>
  <i><%= t ".wallet" %>:<%= number_to_currency(sum_amount current_user) %></i>
</li>
<li class="nav-item">
  <%= link_to t(".bets"), Settings.user_bets_path, class: "nav-link py-3 px-2 bi-house fs-6" %>
</li>
<li>
  <%= link_to t(".charts"), "#", class: "nav-link py-3 px-2 bi-bar-chart-steps fs-6" %>
</li>
<li>
  <%= link_to t(".schedule"), "#", class: "nav-link py-3 px-2 bi-calendar3 fs-6" %>
</li>
<li>
  <%= link_to t(".wallet"), currencies_path, class: "nav-link py-3 px-2 bi-credit-card-2-back-fill fs-6" %>
</li>
<li>
  <%= link_to t(".profile"), current_user, class: "nav-link py-3 px-2 bi-people fs-6" %>
</li>
<li>
  <%= link_to t(".setting"), edit_user_registration_path, class: "nav-link py-3 px-2 bi-wrench fs-6" %>
</li>
<li>
  <%= link_to t(".log_out"), destroy_user_session_path, method: "delete", class: "nav-link py-3 px-2 bi-stop-circle-fill fs-6" %>
</li>